# Generated by Django 5.0.4 on 2024-05-10 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=50)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(max_length=255)),
                ('project_client_name', models.CharField(max_length=50)),
                ('project_client_email', models.EmailField(max_length=254)),
                ('project_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('project_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Project_Lead', to='app.employee')),
                ('project_members', models.ManyToManyField(related_name='Project_Members', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.TextField(max_length=255)),
                ('task_priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('task_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('task_due_date', models.DateTimeField()),
                ('task_created_at', models.DateTimeField(auto_now_add=True)),
                ('task_completed_at', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('task_assigned_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.employee')),
                ('task_assigned_to', models.ManyToManyField(related_name='task_assigned_to', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_name', models.CharField(max_length=50)),
                ('ticket_description', models.TextField(max_length=512)),
                ('ticket_priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('ticket_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('ticket_due_date', models.DateTimeField()),
                ('ticket_raised_by_client', models.BooleanField(default=False)),
                ('ticket_created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_completed_at', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.project')),
                ('ticket_assigned_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.employee')),
                ('ticket_assigned_to', models.ManyToManyField(related_name='ticket_assigned_to', to='app.employee')),
            ],
        ),
    ]
